cc = g++
app = bunde

deps = $(shell find ./ -name "*.h")
src = $(shell find ./ -name "*.cc")
obj = $(src:%.cc=%.o) 

all: $(obj)	
	$(cc) -o $(app) $(obj) -fPIC -lcurl -std=c++17 -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-system -lta_lib

%.o: %.cc $(deps)
	$(cc) -c $< -o $@ -I./api -std=c++17 

clean:
	rm -rf $(obj) $(app)
	
