[package]
name = "ebackend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

egui = "0.24" 
eframe = "0.24"

plotters = "0.3"
plotters-backend = "0.3"
thiserror = "1.0"
anyhow = "1.0"
